### PR TITLE
Correct errors in the readme file related to qvn port for msp430.

### PR DESCRIPTION
**Pull request by ef15c**

### CODE REVIEW

**Comment by quantum-leaps** [comment]
The `README.txt` file in `qpn/ports/msp430/qv/ccs` has been corrected and pushed to the qpn repo. Please check.

**Comment by ef15c** [comment]
It's fine, except for the first paragraph that refers incorrectly to the preemptive QK kernel instead of the cooperative QV kernel.

It appears that the second part of the file, starting with "Using the  Port in CCS" applies to both QV and QK kernels. Why not move this common part in the qpn/ports/msp430 directory?

And the most important thing: thank you for this amazing piece of software. Too bad that it has been phased out without replacement usable with very small microcontrollers.

**Comment by quantum-leaps** [comment]
Got ya. The corrected README.txt have been pused to the qpn repo.

> Too bad that it has been phased out without replacement usable with very small microcontrollers.

Have you tried the qpc framework? It still supports MSP430 and can be configured quite small.

**Comment by ef15c** [comment]
I will try the qpc framework. It will be interresting to see if it can be made sufficiently small to fit the msp430g2553 with only 16 Kbytes of FLASH and 512 bytes of RAM.

**Comment by quantum-leaps** [comment]
qpc should fit in msp430g2553. The 16KB of flash is more than enough. 512 bytes of RAM is a bit tight.

You could play with the configuration macros in `qpc\ports\msp430\qv\qf_port.h` (of course you need to stick to QV as you have no RAM for QK). For example, you can reduce QF_MAX_ACTIVE to less than 8 (whatever number you have in your app). Also, you don't need to initialize publish-subsccribe (don't call QF_psInit()). You might also forego dynamic event management (don't call QF_poolInit()). This means that you will not be able to use event parameters, but a lot can be done with immutable events. All this should reduce your use of RAM.

**Comment by quantum-leaps** [comment]
A new [QP/C example for low-end MSP430G2553](https://github.com/QuantumLeaps/qpc/tree/master/examples/msp430/blinky_msp-exp430g2) device with 16KB or flash ROM and only 512 bytes of RAM demonstrates how to make QP/C extra small. This example configures QP/C not to use dynamic events, but actually, it seems that even that could fit in.
--MMS

**Comment by ef15c** [comment]
Thank you for the QP/C example.

I built it and compared the memory footprints of the QP-nano and QP/C versions:
QP-nano: Flash/FRAM usage is 2486 bytes. RAM usage is 118 bytes.
QP/C: Flash/FRAM usage is 2942 bytes. RAM usage is 135 bytes.

The size requirements of QP/C are still higher than the QP-nano ones, but QP/C can definitively be used on MSP430G2553 MCU.
In conclusion, I will follow your recommendation to use QP/C. I will use QP-nano only as a last resort, if I can't make a QP/C based project fit within the limits imposed by the MCU.

Christian Schoffit

**Comment by ef15c** [comment]
Hello,

To push the subject a little further, I ported the Dining Philosopher Problem on the MSP-EXP430G2 board with the QP/C framework.
I had to replace publish/subscribe by direct event posting and dynamic events by constants events in the flash area.

Is seems working well and has a comparable size as the QP-nano solution:
QP-nano:  Flash/FRAM usage is 4272 bytes. RAM usage is 250 bytes.
QP/C: Flash/FRAM usage is 5004 bytes. RAM usage is 351 bytes.

I would like to share it, to show how much we can do with your software even on low end microcontrollers. I think the right place to do this is the 3rd_party submodule.

What do you think about this?

**Comment by quantum-leaps** [comment]
Sure, please make a pull request in the [contributed](https://github.com/QuantumLeaps/contributed) repo.
--MMS

**Pull request closed without merging**
